# eidolon:mcp start
[mcp_servers.junction]
command = "/home/rynaro/.eidolons/cache/junction@0.4.0/junction"
args = ["mcp","serve"]
[mcp_servers.atomos]
command = "docker"
args = ["run","--rm","-i","--user","1000:1000","--label","eidolons.project=cardboard-box","-v","/home/rynaro/workspace/oss/cardboard-box:/home/rynaro/workspace/oss/cardboard-box:z","-w","/home/rynaro/workspace/oss/cardboard-box","--cap-drop","ALL","--security-opt","no-new-privileges","ghcr.io/rynaro/atomos@sha256:b3f67b4ef64230ebe91aa37efea14e386f178950a2750e0c26c8d29d7ea4a639","serve"]
[mcp_servers.crystalium]
command = "docker"
args = ["run","--rm","-i","--label","eidolons.project=cardboard-box","-v","/home/rynaro/.crystalium/cardboard-box:/root/.crystalium/cardboard-box","-e","CRYSTALIUM_DATA_DIR=/root/.crystalium/cardboard-box","-e","CRYSTALIUM_CALLER_TIER=T1","--cap-drop","ALL","--security-opt","no-new-privileges","ghcr.io/rynaro/crystalium@sha256:75077ffe6b9bcded8f50c0fcb7092ead204128ec4f72af5103df1dfd036f82d5","python","-m","crystalium","serve"]
[mcp_servers.tonberry]
command = "docker"
args = ["run","--rm","-i","--user","1000:1000","--label","eidolons.project=cardboard-box","-v","/home/rynaro/workspace/oss/cardboard-box:/home/rynaro/workspace/oss/cardboard-box:z","-w","/home/rynaro/workspace/oss/cardboard-box","--cap-drop","ALL","--security-opt","no-new-privileges","ghcr.io/rynaro/tonberry@sha256:df6ec882ed2b932483b9cb44449b2e2a233d8e71901e9c6307f627df3979be73","serve"]
# eidolon:mcp end
